import os
import json
import datetime as dt
from io import BytesIO

import requests
import pandas as pd


WOM_GROUP_ID = os.getenv("WOM_GROUP_ID")
WOM_VERIFICATION_CODE = os.getenv("WOM_VERIFICATION_CODE")  # kept for future use; not needed for GET
DISCORD_WEBHOOK_URL = os.getenv("DISCORD_DEV_WH")


def fetch_group_members(group_id: str):
    """
    WOM Get Group Details returns a GroupDetails object that includes `memberships`,
    each with a `player` object. [3](https://birdie0.github.io/discord-webhooks-guide/json.html)
    """
    url = f"https://api.wiseoldman.net/v2/groups/{group_id}"
    r = requests.get(url, timeout=30)
    r.raise_for_status()
    data = r.json()

    memberships = data.get("memberships", [])
    rows = []

    for m in memberships:
        player = m.get("player", {}) or {}
        rows.append({
            "Display Name": player.get("displayName") or player.get("username"),
            "Username": player.get("username"),
            "Role (WOM)": m.get("role"),
            "Status": player.get("status"),
            "Country": player.get("country"),
            "Exp": player.get("exp"),
            "EHP": player.get("ehp"),
            "EHB": player.get("ehb"),
            "Last Imported At": player.get("lastImportedAt"),
            "Membership Created At": m.get("createdAt"),
            "Membership Updated At": m.get("updatedAt"),
        })

    group_name = data.get("name", f"group_{group_id}")
    return group_name, rows


def build_excel_in_memory(group_name: str, rows: list[dict]):
    """
    Builds an .xlsx entirely in memory (no disk write).
    """
    df = pd.DataFrame(rows)
    if df.empty:
        df = pd.DataFrame(columns=[
            "Display Name", "Username", "Role (WOM)", "Status", "Country",
            "Exp", "EHP", "EHB", "Last Imported At",
            "Membership Created At", "Membership Updated At"
        ])

    bio = BytesIO()
    with pd.ExcelWriter(bio, engine="openpyxl") as writer:
        df.to_excel(writer, index=False, sheet_name="Members")

    bio.seek(0)

    ts = dt.datetime.utcnow().strftime("%Y%m%d_%H%M%SZ")
    filename = f"{group_name}_members_{ts}.xlsx".replace(" ", "_")
    return filename, bio, len(df)


def post_file_to_discord(webhook_url: str, filename: str, fileobj: BytesIO, member_count: int, group_name: str):
    """
    Discord webhook file upload: multipart/form-data with `payload_json` plus file field(s). [1](https://stackoverflow.com/questions/77795882/using-class-to-make-discord-bot-for-simple-hello-function)[2](https://realpython.com/how-to-make-a-discord-bot-python/)
    """
    payload = {
        "content": f"Clan member export for **{group_name}**: {member_count} members.\n(Generated by GitHub Actions)"
    }

    files = {
        "file1": (
            filename,
            fileobj,
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        )
    }
    data = {
        "payload_json": json.dumps(payload)
    }

    r = requests.post(webhook_url, data=data, files=files, timeout=60)
    r.raise_for_status()


def main():
    if not WOM_GROUP_ID:
        raise RuntimeError("Missing WOM_GROUP_ID environment variable.")
    if not DISCORD_WEBHOOK_URL:
        raise RuntimeError("Missing DISCORD_DEV_WH environment variable.")

    # WOM_VERIFICATION_CODE is typically used for group management/editing (not needed for read-only GET). [3](https://birdie0.github.io/discord-webhooks-guide/json.html)
    group_name, rows = fetch_group_members(WOM_GROUP_ID)
    filename, bio, member_count = build_excel_in_memory(group_name, rows)
    post_file_to_discord(DISCORD_WEBHOOK_URL, filename, bio, member_count, group_name)

    # Keep logs minimal (no member list printed)
    print(f"✅ Sent Excel to Discord: {member_count} members.")


if __name__ == "__main__":
    main()
