name: Discord Hello World

on:
  workflow_dispatch: {}
  push:
    branches: ["main"]

jobs:
  send_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Post Hello World to Discord webhook
        env:
          DISCORD_DEV_WH: ${{ secrets.DISCORD_DEV_WH }}
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -d '{"content": "Hello world from GitHub Actions"}' \
          $DISCORD_DEV_WH
``
